### ISSUE TITLE
[BUG] IOS Error/warning

### ISSUE THREAD

**Issue by SnailRabbids** [Poing-Studios/godot-admob-ios#28] opened 2022-08-14 15:27 UTC
**Describe the bug**
Big error/warning when loading interstitial on IOS. Ads apears as expected and looks like this error is not a problem, but I'm not sure. Can I ask you to check?

**To Reproduce**
1. Create application on AdMob website, link to Godot application
2. Load interstitial -> Show interstitial -> see error/warning (it might appears after 2-nd or 3-rd load/show)

**Expected behavior**
pass

**Screenshots**
![image](https://user-images.githubusercontent.com/36141552/184543908-d7ce54e4-5e72-491a-955f-33660afef882.png)

**Smartphone (please complete the following information):**
 - Device: iPad 9. gen
 - OS: iOS 15.6
 - Version Godot: 3.4.4

**Additional context**
I dont know what is "WebKit" and why it fails ...

**Comment by gumaciel** [comment] 2022-08-19 23:32
Thank you for opening this Issue, this error crashes your app or stop to serving ads?

**Comment by SnailRabbids** [comment] 2022-08-20 10:14
No, as I can see, this error doing nothing, I don't have any problems because of that, but why is it appears? Mb its something important, idk, just want you to know :)

**Comment by gumaciel** [comment] 2022-10-03 00:55
Hi @SnailRabbids sorry but i couldn't be able to fix it, the errors appear when we try to load again the ad after closing it, i don't know the cause of the errors, could be our implementation, the AdMob SDK or the Godot source code.

I will close this Issue since i couldn't be able to fix it, and seems to not be a big problem to us.

But if anyone is interested in fix this you can re-open the Issue. 

Thank you for opening this issue!

**Closed by gumaciel** 2022-10-03 00:55 UTC
Labels: bug
