### ISSUE TITLE
[BUG] Game freezes when interstitial ad fails to load or show despite connection to API

### ISSUE THREAD

**Issue by toninkush** [Poing-Studios/godot-admob-ios#21] opened 2022-04-21 16:18 UTC
**Describe the bug**
My game freezes/hangs when interstitial fails to load or show. At most times, all the ads including interstitial load and show without a problem. But when it fails to initialize quick enough at the beginning or has no internet connection at that very moment, the game just hangs completely. I have the relevant API signals connected so by right, this shouldn't happen unless I am missing something?

**To Reproduce**
1. Turn off all internet connection on device
2. Trigger interstitial ad in-game
3. My game would freeze as it fails to load the interstitial ad

**Expected behavior**
I have these API signals connected: initialization_complete(status, adapter_name), interstitial_failed_to_load(error_code), interstitial_failed_to_show(error_code). If any of them is triggered or not status ready, the game should have triggered interstitial_closed().

**Smartphone (please complete the following information):**
 - Device: iPhone6+, iPhone13, iPhoneXR (updated)
 - OS: iOS 12.5, 14
 - Version: Godot 3.3.4

**Additional context**
I am not a programmer so if it is not a bug, please do help guide me the right way to fix this. Thank you!

**Comment by toninkush** [comment] 2022-04-22 05:10
Tested on iOS14 with iphone13 and XR. Same problem. Hopefully you could spot the problem. Thanks :)

**Comment by gumaciel** [comment] 2022-04-27 21:04
Hi thank you for reporting it, I will investigate

**Comment by djrain** [comment] 2022-05-19 05:07
Hi, is there any update on this? The plugin looks awesome and we're looking to use it for some projects (hopefully even launching one in the next week or so), but this certainly sounds like a problem if it's indeed a bug... Have not personally tested to confirm this issue yet, but will try it soon. Please let me know if there's anything I can do to help.

**Comment by gumaciel** [comment] 2022-05-19 11:27
Sorry guys I haven't give a look on this yet... If possible please test on any OS Simulator to check if is still happening because I can't test on real devices

**Comment by gumaciel** [comment] 2022-06-23 21:38
@toninkush 

I just tested in versions:

Godot: 3.4.4
AdMob Editor: v1.2.4
iOS Plugin: v2.0.4

And it's working normally as it should, did you or the programmer make any changes to the code to pause? I recommend you redownload the plugins and configure again, maybe that will solve it

Remembering that these are the Plugin methods that are responsible for pausing and unpausing the game when you open an Interstitial, Rewarded or RewardedInterstitial ad:

https://github.com/Poing-Studios/godot-admob-ios/blob/master/plugin/admob/src/formats/Interstitial.mm#L88-L101

This link I sent was only for Interstitial which is what you're saying it's crashing, but try testing with Rewarded and RewardedInterstitial to see if it will solve the problem

I also recommend you test with our test scene:
![Captura de Tela 2022-06-23 às 18 35 12](https://user-images.githubusercontent.com/20030153/175406385-bae98f3f-e614-4db5-9de0-5f7ff248facb.png)
---

If possible also check if these two string are displayed on your XCode Debug when you:

1: Open the Interstitial `interstitialWillPresentScreen`

![Captura de Tela 2022-06-23 às 18 35 53](https://user-images.githubusercontent.com/20030153/175406494-2243f775-d155-4c21-85b6-cbbda2289b17.png)


2: Closes the Interstitial `Ad did dismiss full screen content`

![Captura de Tela 2022-06-23 às 18 36 09](https://user-images.githubusercontent.com/20030153/175406532-f678c8a0-7553-49c8-80d3-56305c498e06.png)

**Comment by toninkush** [comment] 2022-06-24 05:36
Thanks for the reply.

Sorry for my lack of update. I've actually solved this problem with a boolean setup.

Basically, if interstitial is loaded = true, then show interstitial. This stops the game from freezing when there's no internet to load the ad.

I do have a minor problem with getting the banner ad to load faster but that's okay, at least it loads eventually.

**Comment by toninkush** [comment] 2022-06-27 15:42
> @toninkush Nice to know you solved the problem and congrats to your published game!
> 
> Maybe this will solve your another problem with banner load faster:
> 
> 1. Load the banner
> 2. Hide the banner
> 3. Now whenever you want, you can call `MobileAds.show_banner()` and the banner will instantly appear, read more here: [Destroy vs Hide banner godot-admob-android#101 (comment)](https://github.com/Poing-Studios/godot-admob-android/discussions/101#discussioncomment-1903103)
> 

I've actually already been using the load/hide banner methods. The load/show banner methods are in func_ready() itself. Somehow the banner will only show when the player dies and goes back the main screen. Some times longer than that. This doesn't happen on my Android version so I assumed it's just an iOS problem.

> Can you please describe more how you actually get this bug? If this happened to you, it can happen to another people and this need to be solved, i will still try to get this bug.

If you are refering to the interstitial bug where the game freezes failed to load: The easiest way I recreated this bug is just turn off all internet connection (put your phone to flight mode), get the game to trigger load interstitial and then show interstitial ad. Without the solutions above, the game would freeze.

**Comment by gumaciel** [comment] 2022-10-02 02:30
hi @toninkush 

> I've actually already been using the load/hide banner methods. The load/show banner methods are in func_ready() itself. Somehow the banner will only show when the player dies and goes back the main screen. Some times longer than that. This doesn't happen on my Android version so I assumed it's just an iOS problem.

If you think this is a problem, can you please create an Issue with more details of that? I can't reproduce here

> If you are refering to the interstitial bug where the game freezes failed to load: The easiest way I recreated this bug is just turn off all internet connection (put your phone to flight mode), get the game to trigger load interstitial and then show interstitial ad. Without the solutions above, the game would freeze.

I tried here but i still couldn't be able to reproduce, if possible please send a 'Xcode' sample project with a video to show more details

As you said you solved the problem your way and I couldn't reproduce the bug, I'm going to close this Issue, but you can reopen it if you want

That said, I created this Issue which is perhaps an indirect improvement to this Issue: https://github.com/Poing-Studios/godot-admob-editor/issues/51

**Closed by gumaciel** 2022-10-02 02:30 UTC
Labels: bug
