### ISSUE TITLE
[BUG] Error calling method from signal 'consent_info_update_failure'

### ISSUE THREAD

**Issue by NeroNekro** [Poing-Studios/godot-admob-ios#13] opened 2021-12-06 12:24 UTC
**Describe the bug**
I tried to configured my Godot Game with your Admob Plugin and follow the instructions on your site.  After starting it on iOS I got the following Error messages:

```
2021-12-06 13:18:38.510669+0100 [6914:488088] <UMP SDK> To enable debug mode for this device, set: UMPDebugSettings.testDeviceIdentifiers = @[ @"6EA5A6CC-552B-400E-8D49-6ED9D1ABE9FD" ];
2021-12-06 13:18:38.906711+0100 [6914:488088] ERROR: Error calling method from signal 'consent_info_update_failure': 'Node(MobileAds.gd)::_on_AdMob_consent_info_update_failure': Cannot convert argument 2 from bool to String..
2021-12-06 13:18:38.906797+0100 [6914:488088]    at: emit_signal (core/object.cpp:1236) - Error calling method from signal 'consent_info_update_failure': 'Node(MobileAds.gd)::_on_AdMob_consent_info_update_failure': Cannot convert argument 2 from bool to String..
ERROR: Error calling method from signal 'consent_info_update_failure': 'Node(MobileAds.gd)::_on_AdMob_consent_info_update_failure': Cannot convert argument 2 from bool to String..
   at: emit_signal (core/object.cpp:1236) - Error calling method from signal 'consent_info_update_failure': 'Node(MobileAds.gd)::_on_AdMob_consent_info_update_failure': Cannot convert argument 2 from bool to String..
2021-12-06 13:18:42.535940+0100 [6914:488316]  - <Google>[I-ACS012056] Transaction failed. Transaction failed
```

**To Reproduce**
Follow your instruction
Export Godot Project for iOS
Config Xcode
Start it on iPad

**Expected behavior**
Display Ads

**Smartphone (please complete the following information):**
 - Device: iPad 6. Gen
 - OS: iOS
 - Version 15.1

Godot 3.4
MacBook Air

**Additional context**

**Comment by gumaciel** [comment] 2021-12-06 12:30
Hi @NeroNekro , thank you for using our Plugin and sorry for the error.

What iOS and Editor plugin are you using?

e.g.: 

iOS: v2.0.2
Editor: v1.2.1

**Comment by NeroNekro** [comment] 2021-12-06 12:44
> 
Godot Admob Plugin: 1.2.1
iOS: 2.0.2

**Comment by gumaciel** [comment] 2021-12-06 12:45
Also, check if the `Debug/TestEuropeUserConsent` is `true` on Editor to you be able to test the UMP on any part of world.

The consent is for the UMP to obtaining consent of user to use like: 
- deliver personalized ads
- use cookies or other local storage
- use personal data

Read more here: https://developers.google.com/admob/ump/ios/quick-start

**Comment by gumaciel** [comment] 2021-12-07 01:54
@NeroNekro I can confirm the bug of "AdMob Module not initialized" it should not appear because in my case it is initialized, or you are trying to load_banner, or something without wait the "initialization_complete" emit the signal, it is happening on the Example.tscn

I can also confirm the other bug: 

2021-12-06 22:50:45.387058-0300 AdMobAddon[4369:73142] ERROR: Error calling method from signal 'consent_info_update_failure': 'Node(MobileAds.gd)::_on_AdMob_consent_info_update_failure': Cannot convert argument 2 from bool to String..

Probably this bug is happening you haven't configured the UMP because in my case it just happen when i put a `GADApplicationIdentifier` with UMP non configured, but don't worry we will work to fix these two problems, thank you for reporting it.

**Comment by gumaciel** [comment] 2021-12-08 16:48
@NeroNekro please try the new versions:

Editor: https://github.com/Poing-Studios/godot-admob-editor/releases/tag/v1.2.2
iOS: https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v2.0.3

**Comment by gumaciel** [comment] 2021-12-08 19:36
Obs: To see the consent you need to click on "UMP/REQUEST USER CONSENT"
![Captura de Tela 2021-12-08 às 16 35 54](https://user-images.githubusercontent.com/20030153/145272606-7868685e-6a6e-4994-9f5a-760957b28a62.png)

**Comment by NeroNekro** [comment] 2021-12-09 20:40
> @NeroNekro please try the new versions:
> 
> Editor: https://github.com/Poing-Studios/godot-admob-editor/releases/tag/v1.2.3 iOS: https://github.com/Poing-Studios/godot-admob-ios/releases/tag/v2.0.4

Thanks. I didn't get any error message:
`2021-12-09 21:31:10.333148+0100 Geminus[1893:164364] init admob plugin
2021-12-09 21:31:10.333230+0100 Geminus[1893:164364] initialize admob
2021-12-09 21:31:10.341372+0100 Geminus[1893:164364] ERROR: No library set for this platform
2021-12-09 21:31:10.341458+0100 Geminus[1893:164364]    at: initialize (modules/gdnative/gdnative.cpp:293) - No library set for this platform
ERROR: No library set for this platform
   at: initialize (modules/gdnative/gdnative.cpp:293) - No library set for this platform

2021-12-09 21:31:11.249995+0100 Geminus[1893:164364] AdMob Module will try to initialize now
2021-12-09 21:31:11.296624+0100 Geminus[1893:164364] on Testing Real Device: testDeviceIdentifiers: 9f89c84a559f573636a47ff80000000
2021-12-09 21:31:11.297109+0100 Geminus[1893:164364] maxAdContentRating = GADMaxAdContentRatingParentalGuidance
2021-12-09 21:31:11.939332+0100 Geminus[1893:164493]  - <Google>[I-ACS025031] AdMob App ID changed. Original, new: (nil), ca-app-pub-5704334797256128~000000000
2021-12-09 21:31:11.953987+0100 Geminus[1893:164364] GADMobileAds : True
2021-12-09 21:31:11.954047+0100 Geminus[1893:164364] AdMob Module has been initialized
2021-12-09 21:31:12.178736+0100 Geminus[1893:164493]  - <Google>[I-ACS023007] Analytics v.80901000 started
2021-12-09 21:31:12.178891+0100 Geminus[1893:164493]  - <Google>[I-ACS023008] To enable debug logging set the following application argument: -APMAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)

2021-12-09 21:31:13.481179+0100 Geminus[1893:164498]  - <Google>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2021-12-09 21:31:14.593508+0100 Geminus[1893:164501]  - <Google>[I-ACS023012] Analytics collection enabled`

But the example scene didn't show any banner. I activated UMP and if I press the Button REQUEST USER CONSENT, nothing happens.

Is this my fault and a bad configuration or what is the problem?

**Comment by gumaciel** [comment] 2021-12-10 23:40
@NeroNekro well, for me it seems to work normally, it's not appearing for me because is saying this: 

`consent_info_update_success Consent Form not Available`

But i will investigate this, probably is something missing on our configuration.


Btw be sure to mark this for testing:
![Captura de Tela 2021-12-10 às 20 40 33](https://user-images.githubusercontent.com/20030153/145654304-2c01365c-4d28-4c83-a982-f3086e3e058d.png)

**Comment by gumaciel** [comment] 2021-12-10 23:58
![Captura de Tela 2021-12-10 às 20 57 07](https://user-images.githubusercontent.com/20030153/145655253-fc1c27c1-b37c-45db-84f0-12cb27c985b0.png)

Please try with this binary, probably will fix this
[admob.zip](https://github.com/Poing-Studios/godot-admob-ios/files/7696029/admob.zip)

**Comment by gumaciel** [comment] 2021-12-20 13:42
Hi @NeroNekro , have you tested with this binary?

[admob.zip](https://github.com/Poing-Studios/godot-admob-ios/files/7696029/admob.zip) 

as i'm seeing everything seems to work now

**Comment by NeroNekro** [comment] 2022-01-16 14:35
> Hi @NeroNekro , have you tested with this binary?
> 
> [admob.zip](https://github.com/Poing-Studios/godot-admob-ios/files/7696029/admob.zip)
> 
> as i'm seeing everything seems to work now

sry for my late response, I was very busy. today I try your new version.

**Comment by NeroNekro** [comment] 2022-01-16 15:20
ok, maybe I'm too stupid for this :D

I didnt get any Consent  Banner or something else. I made some screenshots to be sure that's my config is correct.

```
2022-01-16 15:58:38.033610+0100 Geminus[2813:374506] AdMob Module will try to initialize now
2022-01-16 15:58:38.041352+0100 Geminus[2813:374506] on Testing Real Device: testDeviceIdentifiers: 9f89c84a559f573636a47ff8daed0d33
2022-01-16 15:58:38.045460+0100 Geminus[2813:374506] maxAdContentRating = GADMaxAdContentRatingParentalGuidance
2022-01-16 15:58:38.167988+0100 Geminus[2813:374657]  - <Google>[I-ACS025031] AdMob App ID changed. Original, new: (nil), ca-app-pub-5704334797256128~7787148262
2022-01-16 15:58:38.168574+0100 Geminus[2813:374657]  - <Google>[I-ACS023007] Analytics v.80901000 started
2022-01-16 15:58:38.169083+0100 Geminus[2813:374657]  - <Google>[I-ACS023008] To enable debug logging set the following application argument: -APMAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2022-01-16 15:58:38.171969+0100 Geminus[2813:374662]  - <Google>[I-ACS023171] Resetting App Measurement data
2022-01-16 15:58:38.177053+0100 Geminus[2813:374662]  - <Google>[I-ACS023014] Failed to delete old database file. Error: Error Domain=NSCocoaErrorDomain Code=4 "“google-app-measurement.sql” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/var/mobile/Containers/Data/Application/7DAEEB9E-5A0F-47CD-905D-A03EE93885C1/Library/Application Support/Google/Measurement/google-app-measurement.sql, NSUnderlyingError=0x280125950 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2022-01-16 15:58:39.699533+0100 Geminus[2813:374506] GADMobileAds : True
2022-01-16 15:58:39.699671+0100 Geminus[2813:374506] AdMob Module has been initialized
2022-01-16 15:58:40.070268+0100 Geminus[2813:374665]  - <Google>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2022-01-16 15:58:42.216561+0100 Geminus[2813:374667]  - <Google>[I-ACS023012] Analytics collection enabled

2022-01-16 15:58:51.796265+0100 Geminus[2813:374667]  - <Google>[I-ACS012056] Transaction failed. Transaction failed
```
![Godot_2022-01-16 16-07-50@2x](https://user-images.githubusercontent.com/36452325/149666066-a8dd3d3a-5a61-49f8-889f-831794dd72d6.jpg)
![Godot_2022-01-16 16-08-19@2x](https://user-images.githubusercontent.com/36452325/149666067-a4d1244f-dd3a-4ab8-ab94-740cd3316f86.jpg)
![Godot_2022-01-16 16-08-43@2x](https://user-images.githubusercontent.com/36452325/149666068-c33a4d6b-d36c-4d3d-bee8-d5fff1566be3.jpg)
![Godot_2022-01-16 16-10-07@2x](https://user-images.githubusercontent.com/36452325/149666070-d69f7980-c97d-4b61-998b-607e7818ba44.jpg)
![image0](https://user-images.githubusercontent.com/36452325/149666072-21c911f0-afcd-445a-8268-7870398ce3ef.png)
![Teampaper Snap_2022-01-16 16-06-30@2x](https://user-images.githubusercontent.com/36452325/149666073-883e5c0b-47d0-4bde-9bb6-675eb22e2fdf.jpg)
![Xcode_2022-01-16 16-10-57@2x](https://user-images.githubusercontent.com/36452325/149666075-7e57af28-d822-43fc-8b41-34cfe3f83801.jpg)

**Comment by NeroNekro** [comment] 2022-01-16 21:10
Another question. In GitHub wiki I saw the following instruction:

_The usage is pretty simple, after you Copied the ./admob_api/ to your Game Project and added the res://admob_api/MobileAds.tscn on AutoLoad as Singleton you now will be able to call all available function of the API, such as MobileAds.load_banner()_

In the package I didn't find any scene with this name. Is this an old version?

**Comment by gumaciel** [comment] 2022-01-16 21:36
Hi, yes the ` ./admob_api/` is from older version, please ignore it

strange that the buttons were not activated, did you make any changes to the AdMob code (MobileAds.gd or Example.gd)?

**Comment by gumaciel** [comment] 2022-01-16 21:37
Also, to the UMP Appear you need to click on "REQUEST USER CONSENT"

![image](https://user-images.githubusercontent.com/20030153/149679051-8cac02ad-eb5d-4150-9db1-2c03a7b5248f.png)

**Comment by NeroNekro** [comment] 2022-01-16 22:20
> Hi, yes the ` ./admob_api/` is from older version, please ignore it
> 
> strange that the buttons were not activated, did you make any changes to the AdMob code (MobileAds.gd or Example.gd)?

I didn't change anything.
Only add this to my button pressed:
get_tree().change_scene("res://addons/admob/test/Example.tscn")



> Also, to the UMP Appear you need to click on "REQUEST USER CONSENT"
> 
> ![image](https://user-images.githubusercontent.com/20030153/149679051-8cac02ad-eb5d-4150-9db1-2c03a7b5248f.png)

Pushing the button do nothing. Seems also disabled. In the log from Xcode no log show up

**Comment by gumaciel** [comment] 2022-01-18 00:35
Sorry for that, tomorrow I will try to do a mini video tutorial with the new version, maybe it will help you

**Comment by gumaciel** [comment] 2022-01-20 01:50
@NeroNekro please watch this video, i did very fast sorry about this: https://www.youtube.com/watch?v=i_RuHq0aWTY&feature=youtu.be 

it's being very busy for me these days

**Comment by gumaciel** [comment] 2022-03-10 21:27
Closing this issue due the time, by my tests the problem was solved, if the problem for you has not solved please re-open this issue

**Closed by gumaciel** 2022-03-10 21:27 UTC
Labels: bug
